%% Ruairidh Barlow
% ECG and Accelerometer signal processing
% Revised: 1/21/2020

%%
function ECG = importfile(filename, dataLines)
%IMPORTFILE Import data from a text file
%  ECG = IMPORTFILE(FILENAME) reads data from text file FILENAME for the
%  default selection.  Returns the data as a table.
%
%  ECG = IMPORTFILE(FILE, DATALINES) reads data for the specified row
%  interval(s) of text file FILENAME. Specify DATALINES as a positive
%  scalar integer or a N-by-2 array of positive scalar integers for
%  dis-contiguous row intervals.
%
%  Example:
%  ECG = importfile("C:\Users\ruair\Documents\MATLAB\ECG.csv", [3, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 12-Jul-2019 08:17:56

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [3, Inf];
end

%% Setup the Import Options
opts = delimitedTextImportOptions("NumVariables", 1);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = "EpochTimestamp1527265609";
opts.VariableTypes = "double";
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
ECG = readtable(filename, opts);

%% Convert to output type
ECG = table2array(ECG);

end